"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express_1 = require("express");
const authenticate_jwt_1 = require("../middlewares/authenticate-jwt");
const UserController_1 = require("../controllers/UserController");
exports.userRouter = (0, express_1.Router)();
const userController = new UserController_1.UserController();
exports.userRouter.post('/auth/login', userController.login);
exports.userRouter.get('/users', authenticate_jwt_1.myMiddleware, userController.users);
